from __future__ import annotations

from typing import Protocol, runtime_checkable

import numpy as np


@runtime_checkable
class InferenceEngine(Protocol):
    def tokenize(self, text: str) -> list[int]: ...

    def detokenize(self, tokens: list[int]) -> str: ...

    def process_tokens(self, tokens: list[int]) -> None: ...

    def generate_next(self) -> int: ...

    def get_kv_cache_token_count(self) -> int: ...

    def evict_ranges(self, ranges: list[tuple[int, int]]) -> None: ...

    def kv_block_save(self, p0: int, p1: int, seq_id: int = 0) -> bytes: ...

    def kv_block_load(self, data: bytes, new_p0: int, seq_id: int = 0) -> bool: ...

    def get_embeddings(self, token_positions: list[int]) -> np.ndarray: ...

    @property
    def next_write_pos(self) -> int: ...

    @property
    def n_ctx(self) -> int: ...

    def reset(self) -> None: ...

    @property
    def n_embd(self) -> int: ...

    @property
    def eos_token(self) -> int: ...
